version: "3"

services:
  drone:
    image: drone/drone:latest
    container_name: drone-io
    restart: unless-stopped
    environment:
      DRONE_GITHUB_CLIENT_ID: ${DRONE_GITHUB_CLIENT_ID}
      DRONE_GITHUB_CLIENT_SECRET: ${DRONE_GITHUB_CLIENT_SECRET}
      DRONE_RPC_SECRET: ${DRONE_RPC_SECRET}
      DRONE_SERVER_HOST: ${DRONE_SERVER_HOST}
      DRONE_SERVER_PROTO: ${DRONE_SERVER_PROTO}
      DRONE_USER_CREATE: ${DRONE_USER_CREATE}
      DRONE_USER_FILTER: ${DRONE_USER_FILTER}
    #ports:
    #  - 80:80
    #  - 443:443
    volumes:
      - ./data:/data
    networks:
      - letsencrypt_default
      - backend

  drone-runner:
    image: drone/drone-runner-docker:1
    container_name: drone-docker-runner
    restart: unless-stopped
    environment:
      DRONE_RPC_PROTO: ${DRONE_RPC_PROTO}
      DRONE_RPC_HOST: ${DRONE_RPC_HOST}
      DRONE_RPC_SECRET: ${DRONE_RPC_SECRET}
      DRONE_RUNNER_CAPACITY: 2
      DRONE_RUNNER_NAME: ${DRONE_RUNNER_NAME}
    #ports:
    #  - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend

networks:
  letsencrypt_default:
    external: true
  backend:
    name: drone_backend
    driver: bridge
