version: '2'
services:
  droppy:
    container_name: droppy
    image: silverwind/droppy
    volumes:
      - ./config:/config
      - ./data:/files
    restart: unless-stopped
    networks:
      - letsencrypt_default
    
networks:
  letsencrypt_default:
    external: true
    
