---
version: "2"
services:
  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=--CHANGE THIS--
      - DB_DATABASE=thisdb
      - APP_URL=--YOUR URL--
    volumes:
      - ./config:/config
    restart: unless-stopped
    depends_on:
      - bookstack_db
    networks:
      - letsencrypt_default

  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=--RANDOM THIS--
      - TZ=Europe/London
      - MYSQL_DATABASE=thisdb
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=--CHANGE THIS--
    volumes:
      - ./db:/config
    restart: unless-stopped
    networks:
      - letsencrypt_default

networks:
  letsencrypt_default:
    external: true