---
version: "2.1"
services:
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
      - DELUGE_LOGLEVEL=error #optional    
    volumes:
      - ./config:/config        
      - ./downloads:/downloads  
      # necessary for the torrent network. Can't reverse proxy these
    ports:
      - 6882:6882/udp
      - 6882:6882
    restart: unless-stopped
    networks:
      - letsencrypt_default

networks:
  letsencrypt_default:
    external: true