version: '3'

services:

  linkding:
    container_name: linkding
    image: sissbruecker/linkding:latest
    volumes:
      - ./data:/etc/linkding/data
    restart: unless-stopped
    networks:
      - letsencrypt_default

networks:
  letsencrypt_default:
    external: true